// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMpnpPHf_Eq0g1l8OucloN98tkaQ7eRIM',
    appId: '1:568396119393:android:229da24c05081d0f9ad920',
    messagingSenderId: '568396119393',
    projectId: 'nutritrack-auth',
    storageBucket: 'nutritrack-auth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNut-ocHMYobGKeur-zZNJHN2vNY8rc0o',
    appId: '1:568396119393:ios:8df78b60bc21d91d9ad920',
    messagingSenderId: '568396119393',
    projectId: 'nutritrack-auth',
    storageBucket: 'nutritrack-auth.appspot.com',
    iosBundleId: 'com.example.pkmNutritrack',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_5EXs97pFQ-gV0trjoRrtIhDnTShctms',
    authDomain: 'nutritrack-auth.firebaseapp.com',
    projectId: 'nutritrack-auth',
    storageBucket: 'nutritrack-auth.appspot.com',
    messagingSenderId: '568396119393',
    appId: '1:568396119393:web:6884a08ad59661349ad920',
    measurementId: 'G-JP6T09ZL73',
  );

}